# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-a
#   labels:
#     app: app-a
# spec:
#   replicas: 
#   selector:
#     matchLabels:
#       app: app-a
#   template:
#     metadata:
#       labels:
#         app: app-a
#     spec:
#       containers:
#       - name: app-a
#         image: nginx:1.14.2
#         ports:
#         - containerPort: 80