{{range $index, $item := .Values.appArray }}
{{ $appName := printf "app-replica-%d" $index }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
spec:
  replicas: 
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      containers:
      - name: {{$appName}}
        image: nginx:1.14.2
        ports:
        - containerPort: {{$item.port}}
{{ end }}